# Generated by Django 5.2.3 on 2025-07-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pai_id', models.IntegerField()),
                ('pay_option', models.CharField(max_length=100)),
                ('min_pay', models.IntegerField()),
            ],
        ),
    ]
