# Generated by Django 5.2.4 on 2025-07-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0004_alter_relationonetomany_student_and_more'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RelationOneToMany',
            new_name='RelationManyToOne',
        ),
    ]
