# Generated by Django 5.2.4 on 2025-07-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='views',
            name='id',
        ),
        migrations.AddField(
            model_name='views',
            name='view_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='views',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
