# Generated by Django 5.2.4 on 2025-07-20 17:06

import model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pic',
            field=models.FileField(null=True, upload_to='pics/% Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='students',
            name='userpic',
            field=models.FileField(blank=True, null=True, upload_to=model.models.user_image_path),
        ),
        migrations.AlterField(
            model_name='students',
            name='batch',
            field=models.IntegerField(),
        ),
    ]
