# Generated by Django 5.2.4 on 2025-07-20 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_students_pic_students_userpic_alter_students_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('husband_age', models.IntegerField(blank=True)),
                ('age', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('husband_batch', models.IntegerField(blank=True)),
                ('husband_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wife', to='model.mans')),
            ],
        ),
    ]
