# Generated by Django 5.2.4 on 2025-07-20 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_mans_wife'),
    ]

    operations = [
        migrations.CreateModel(
            name='Womens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Couples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('husband_age', models.IntegerField(blank=True, null=True)),
                ('wife_age', models.IntegerField(blank=True, null=True)),
                ('husband_batch', models.IntegerField(blank=True, null=True)),
                ('wife_batch', models.IntegerField(blank=True, null=True)),
                ('husband', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.mans')),
                ('wife', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='model.womens')),
            ],
        ),
        migrations.DeleteModel(
            name='Wife',
        ),
    ]
