# Generated by Django 5.2.4 on 2025-07-21 07:22

import model.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_womens_couples_delete_wife'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='group',
            field=models.CharField(choices=[('sci', 'Science'), ('arts', 'Arts'), ('com', 'Commerce')], default='sci', max_length=10),
        ),
        migrations.AlterField(
            model_name='couples',
            name='husband_age',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='couples',
            name='husband_batch',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='couples',
            name='wife_age',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='couples',
            name='wife_batch',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(validators=[model.models.ageValidtor]),
        ),
    ]
