# Generated by Django 5.2.4 on 2025-07-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_students_group_alter_couples_husband_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='slug',
            field=models.SlugField(blank=True, max_length=20, unique=True),
        ),
    ]
