# Generated by Django 5.2.4 on 2025-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_students_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
