# Generated by Django 5.2.4 on 2025-07-21 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_alter_students_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='slug',
        ),
    ]
