# Generated by Django 5.2.4 on 2025-08-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('batch', models.IntegerField()),
                ('group', models.CharField(choices=[('sci', 'Science'), ('arts', 'Arts'), ('com', 'Commerce')], default='sci', max_length=10)),
            ],
        ),
    ]
